### ISSUE TITLE
Check update?

### ISSUE THREAD

**Issue by wongpk** [jeremyclark13/automatic-theme-plugin-update#11]
I find it hard to check the update version without  uncomment this line: // set_site_transient('update_themes', null); 

Is there anyway for the theme itself check the update themselves?

Thank you!

**Comment by jeremyclark13** [comment]
It sounds like the WordPress update check itself isn't running as it should.  Normally the update check doesn't run but everyone 24 hours.  Does your site show if there are plugin/theme updates normally.  This line will have to commented out if you release the theme to the public otherwise everytime the site where it's used is loaded it will hit your server and cause unnecessary load.

**Comment by wongpk** [comment]
I see, perhaps, I'm just too rush for that. Thanks for the head up.
