### ISSUE TITLE
More Clear Directions for Multi-Plugin/Theme Users

### ISSUE THREAD

**Issue by chriscct7** [jeremyclark13/automatic-theme-plugin-update#9]
I want to use this to distribute updates to my (at current time) 7 plugins and 3 themes. I presume, on the api side, I just need to copy and paste the template for the theme and plugin information over and over and just change the slug contained in packages['slug']. However, what do I need to change on the update.php file. It says that I need to prefix all functions. I presume that only applies to update.php. Although, one question I do have is does it matter what I prefix them with? In other words, if I prefix them with 'ex' do I need to prefix anything on the api side with 'ex'. I am assuming no, because the api side uses the slug of the plugin/theme.
Is this correct?

FYI, I really appreciate the amount of time spent making this, and as soon as I get our new site up and running (just got to get the update feature working), I might spend a couple blog posts on your plugin if you don't mind :) .

**Comment by jeremyclark13** [comment]
Yes you just copy the package array and change the slug and version info for each new plugin or theme. 

It doesn't matter what you prefix the functions with as long as its unique to that plugin or theme. Also keep in mind the global variables should be prefixed as well. This is just to keep from getting function exists errors. You won't have to do anything on the API side. 

Writeups about this are always welcome. I'm also hoping to have time to convert this into a full blown web app, that I might sell, with an admin panel to make update tasks easier. 

Chris Christoff reply@reply.github.com wrote:

I want to use this to distribute updates to my (at current time) 7 plugins and 3 themes. I presume, on the api side, I just need to copy and paste the template for the theme and plugin information over and over and just change the slug contained in packages['slug']. However, what do I need to change on the update.php file. It says that I need to prefix all functions. I presume that only applies to update.php. Although, one question I do have is does it matter what I prefix them with? In other words, if I prefix them with 'ex' do I need to prefix anything on the api side with 'ex'. I am assuming no, because the api side uses the slug of the plugin/theme.
Is this correct?

FYI, I really appreciate the amount of time spent making this, and as soon as I get our new site up and running (just got to get the update feature working), I might spend a couple blog posts on your plugin if you don't mind :) .

---

Reply to this email directly or view it on GitHub:
https://github.com/jeremyclark13/automatic-theme-plugin-update/issues/9

**Comment by chriscct7** [comment]
Ok thank you.
Noticed you created the Software Add-on for Jigoshop, and actually I am
going to be using this plugin to help me distribute plugins for Jigoshop as
well (Duplicate Product, (coming soon) CSV Loader, (coming soon)
WooCommerce to Jigoshop).
Thank you for your support of the Jigoshop community

-Chris

**Comment by chriscct7** [comment]
Ok I am having issues with getting this to work. I am using the key required download, but I believe my issue starts before I get to that point. Do you have an email I can send a zip with a copy of the plugin and configuration I have and you can see what I am doing wrong?

**Comment by jeremyclark13** [comment]
jeremy@clark-technet.com

Chris Christoff reply@reply.github.com wrote:

Ok I am having issues with getting this to work. I am using the key required download, but I believe my issue starts before I get to that point. Do you have an email I can send a zip with a copy of the plugin and configuration I have and you can see what I am doing wrong?

---

**Comment by chriscct7** [comment]
Its on the way.

-Chris

**Comment by chriscct7** [comment]
When I try to manually update it using the built in WordPress plugin feature it says that it is the latest version. Obviously my server side says the new version is 1.1 and I've tried setting the installed version to 0.1.

**Comment by chriscct7** [comment]
Just decided to try something different. Modified the api to use MD5 hashes, and I like how it works now. Closing this for now.
